#objects = main.o add_fun.o

add: 
	gcc -I hdr src/*.c -o add

#main.o: ../src/main.c ../hdr/header.h
#	gcc -c ../src/main.c
#add_fun.o: ../src/add_fun.c ../hdr/header.h
#	gcc -c ../src/add_fun.c

clean: 
	rm -rf *.o
